project:
  type: website
  output-dir: "docs"

website:
  title: "EACSIII-2024-1"
  site-url: https://fcpys.github.io/eacsiii2024_1/
  repo-url: https://github.com/fcpys/eacsiii2024_1/
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: equipo.qmd
        text: Equipo docente
      - href: about.qmd
        text: Programa 
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Instalar R"
        contents:
          - instala.qmd

format:
  html:
    theme: 
      light: lumen
      dark: darkly
    css: styles.css
    toc: true

editor: visual

